### ISSUE TITLE
array_slice(): Passing null to parameter #2 ($offset) of type int is deprecated

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#20]
We get this error a lot when decoding a few things in the lib. Even though it is just a `deprecated` error, when using some libs like `OpenSwoole` this will throw an exception and stop executing the coroutine. We need to adapt the code, so this doesn't happen.

```
PHP Fatal error:  Uncaught ErrorException: array_slice(): Passing null to parameter #2 ($offset) of type int is deprecated in /home/custodio/Development/Enjin/open-platform-app/vendor/gmajor/substrate-codec-php/src/Codec/ScaleBytes.php:53
Stack trace:
#0 [internal function]: Phrity\Util\ErrorHandler->Phrity\Util\{closure}()
#1 /home/custodio/Development/Enjin/open-platform-app/vendor/gmajor/substrate-codec-php/src/Codec/ScaleBytes.php(53): array_slice()
#2 /home/custodio/Development/Enjin/open-platform-app/vendor/gmajor/substrate-codec-php/src/Codec/Types/ScaleInstance.php(198): Codec\ScaleBytes->nextBytes()
#3 /home/custodio/Development/Enjin/open-platform-app/vendor/gmajor/substrate-codec-php/src/Codec/Types/Metadata.php(31): Codec\Types\ScaleInstance->nextBytes()
#4 /home/custodio/Development/Enjin/open-platform-app/vendor/gmajor/substrate-codec-php/src/Codec/Types/ScaleInstance.php(134): Codec\Types\Metadata->decode()
```

**Comment by gmajor-encrypt** [comment]
@leonardocustodio This issue has been fixed.
